### ISSUE TITLE
Script does not handle different # channels per cycle

### ISSUE THREAD

**Issue by rjp21** [hungyiwu/pca_analysis_toolkit#4]
the dnacorr() function in run.py currently uses "for ch in range(0, len(array_list), 4):" to get the data for DNA channels since DNA normally in the first channel of the cycle, and usually each cycle has 4 channels each. Sometimes we alter number of channels per cycle (ie. cycle 0 = 5 channels, cycle 1 = 4 channels, cycle 2 = 5 channels ...) so this code does not work. To allow for different numbers of channels I have been creating an array holding the indices of all DNA channels for the input ome.tif (ie dna_indices = [ 0, 5, 10, 15,20, 25, 29, 33 ]; for ch in dna_indices: ) though this is not an efficient use of time in scaling up. It would be extremely useful to extract the indices of DNA channels using the markers.csv file so like "if row starts with "DNA", append index to dna_indices" instead of manually creating the array or just assuming the number of channels per cycle.

**Comment by hungyiwu** [comment]
Is there an example image with varying number of channels per cycle that I can test on?

**Comment by rjp21** [comment]
/n/scratch2/rjp21/Z170 all the files here have either 5 or 4 channels per cycle. markers.csv is here as well. Another issue that might be good to handle here is when slides break or the tissue is damaged, they will be pulled out early so not contain some of the later cycles (ie. slide1 could have all 8 cycles, but slide 9 could only have 2). it would be nice to pass by if it tries to go to a DNA index that does not exist instead of throwing an error and stopping the whole run. I was previously altering the dna_indices array for each slide.

**Comment by hungyiwu** [comment]
Feature to add:
* Handle different number of channels per cycle
* Handle different number of cycles per slide

**Comment by hungyiwu** [comment]
@rjp21 
I implemented and merged these into the branch `develop`:
* Only calculate DNA correlation coefficient for markers whose names start with "DNA" or "DNA_"
* If there are less channels in the ome.tif file than in the marker list, then truncate the marker list.  
  If there are more channels than the markers, than print out warning message and skip the image.

Does these fit our need? If so, I'll close this issue

**Comment by rjp21** [comment]
That sounds perfect. I'd say its good to close, but I also want to test it out. did you test with a slide form the Z170 dataset? I will find a different dataset to run as well.

Thanks so much for the update, it's a nice upgrade.

Best,

Roxy
________________________________

**Comment by hungyiwu** [comment]
I tested it on `1.ome.tif` in the Z170 folder. I'll close it for now but please let me know if it works on other data on your end!
